//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWayPOS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Ums
    {
        public Products_Ums()
        {
            this.PurchaseOrderDetail_Ums = new HashSet<PurchaseOrderDetail_Ums>();
        }
    
        public int id { get; set; }
        public int product_code { get; set; }
        public int um_code { get; set; }
        public Nullable<int> disposed_um_code { get; set; }
        public Nullable<short> disposed_um_qty { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Um Um { get; set; }
        public virtual Um Disposed_ProductUm { get; set; }
        public virtual ICollection<PurchaseOrderDetail_Ums> PurchaseOrderDetail_Ums { get; set; }
    }
}
