//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWayPOS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductArrival
    {
        public ProductArrival()
        {
            this.PurchaseOrderHeaders = new HashSet<PurchaseOrderHeader>();
        }
    
        public int product_arrival_code { get; set; }
        public string product_arrival_description { get; set; }
    
        public virtual ICollection<PurchaseOrderHeader> PurchaseOrderHeaders { get; set; }
    }
}
