//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWayPOS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail_Ums
    {
        public int purchase_order_detail_id { get; set; }
        public int purchase_order_detail_um_id { get; set; }
        public int quantity { get; set; }
        public int products_ums_id { get; set; }
    
        public virtual PurchaseOrderDetail PurchaseOrderDetail { get; set; }
        public virtual Products_Ums Products_Ums { get; set; }
    }
}
