//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWayPOS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierCategory
    {
        public SupplierCategory()
        {
            this.Suppliers = new HashSet<Supplier>();
        }
    
        public int supplier_category_code { get; set; }
        public string supplier_category_name { get; set; }
    
        public virtual ICollection<Supplier> Suppliers { get; set; }
    }
}
