//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWayPOS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Um
    {
        public Um()
        {
            this.Products = new HashSet<Product>();
            this.Products_Ums = new HashSet<Products_Ums>();
            this.Products_Ums1 = new HashSet<Products_Ums>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
            this.Um1 = new HashSet<Um>();
        }
    
        public int um_code { get; set; }
        public string um_shortname { get; set; }
        public string um_fullname { get; set; }
        public bool disposable { get; set; }
        public Nullable<int> disposed_um_code { get; set; }
        public Nullable<short> disposed_um_qty { get; set; }
        public Nullable<bool> depend_on_product { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Products_Ums> Products_Ums { get; set; }
        public virtual ICollection<Products_Ums> Products_Ums1 { get; set; }
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual ICollection<Um> Um1 { get; set; }
        public virtual Um Disposed_Um { get; set; }
    }
}
